# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: rgb(16, 39, 112);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_Main = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Main.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_Main.setObjectName("horizontalLayout_Main")
        self.frame_LeftPanel = QtWidgets.QFrame(self.centralwidget)
        self.frame_LeftPanel.setObjectName("frame_LeftPanel")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_LeftPanel)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_LeftPanel = QtWidgets.QVBoxLayout()
        self.verticalLayout_LeftPanel.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_LeftPanel.setObjectName("verticalLayout_LeftPanel")
        self.label_Favorites = QtWidgets.QLabel(self.frame_LeftPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Favorites.sizePolicy().hasHeightForWidth())
        self.label_Favorites.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label_Favorites.setFont(font)
        self.label_Favorites.setStyleSheet("color: rgb(89, 189, 244);")
        self.label_Favorites.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Favorites.setObjectName("label_Favorites")
        self.verticalLayout_LeftPanel.addWidget(self.label_Favorites)
        self.scrollArea_Favorites = QtWidgets.QScrollArea(self.frame_LeftPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_Favorites.sizePolicy().hasHeightForWidth())
        self.scrollArea_Favorites.setSizePolicy(sizePolicy)
        self.scrollArea_Favorites.setStyleSheet("background-color: rgb(172, 208, 234);\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: rgb(102, 126, 173);")
        self.scrollArea_Favorites.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea_Favorites.setLineWidth(0)
        self.scrollArea_Favorites.setWidgetResizable(True)
        self.scrollArea_Favorites.setObjectName("scrollArea_Favorites")
        self.scrollAreaWidgetContents_Favorites = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_Favorites.setGeometry(QtCore.QRect(0, 0, 349, 239))
        self.scrollAreaWidgetContents_Favorites.setObjectName("scrollAreaWidgetContents_Favorites")
        self.scrollArea_Favorites.setWidget(self.scrollAreaWidgetContents_Favorites)
        self.verticalLayout_LeftPanel.addWidget(self.scrollArea_Favorites)
        self.label_SearchHistory = QtWidgets.QLabel(self.frame_LeftPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SearchHistory.sizePolicy().hasHeightForWidth())
        self.label_SearchHistory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label_SearchHistory.setFont(font)
        self.label_SearchHistory.setStyleSheet("color: rgb(89, 189, 244);")
        self.label_SearchHistory.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SearchHistory.setObjectName("label_SearchHistory")
        self.verticalLayout_LeftPanel.addWidget(self.label_SearchHistory)
        self.scrollArea_SearchHistory = QtWidgets.QScrollArea(self.frame_LeftPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_SearchHistory.sizePolicy().hasHeightForWidth())
        self.scrollArea_SearchHistory.setSizePolicy(sizePolicy)
        self.scrollArea_SearchHistory.setStyleSheet("background-color: rgb(172, 208, 234);\n"
"border-style: outset;\n"
"border-width: 5px;\n"
"border-color: rgb(102, 126, 173);\n"
"\n"
"")
        self.scrollArea_SearchHistory.setWidgetResizable(True)
        self.scrollArea_SearchHistory.setObjectName("scrollArea_SearchHistory")
        self.scrollAreaWidgetContents_SearchHistory = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_SearchHistory.setGeometry(QtCore.QRect(0, 0, 349, 655))
        self.scrollAreaWidgetContents_SearchHistory.setObjectName("scrollAreaWidgetContents_SearchHistory")
        self.scrollArea_SearchHistory.setWidget(self.scrollAreaWidgetContents_SearchHistory)
        self.verticalLayout_LeftPanel.addWidget(self.scrollArea_SearchHistory)
        self.verticalLayout_LeftPanel.setStretch(0, 1)
        self.verticalLayout_LeftPanel.setStretch(1, 6)
        self.verticalLayout_LeftPanel.setStretch(2, 1)
        self.verticalLayout_LeftPanel.setStretch(3, 16)
        self.verticalLayout_7.addLayout(self.verticalLayout_LeftPanel)
        self.horizontalLayout_Main.addWidget(self.frame_LeftPanel)
        self.frame_RightPanel = QtWidgets.QFrame(self.centralwidget)
        self.frame_RightPanel.setStyleSheet("background-color: rgb(172, 208, 234);\n"
"")
        self.frame_RightPanel.setObjectName("frame_RightPanel")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_RightPanel)
        self.verticalLayout_9.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_RightPanel = QtWidgets.QVBoxLayout()
        self.verticalLayout_RightPanel.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_RightPanel.setSpacing(0)
        self.verticalLayout_RightPanel.setObjectName("verticalLayout_RightPanel")
        self.horizontalLayout_TopButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_TopButtons.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_TopButtons.setObjectName("horizontalLayout_TopButtons")
        spacerItem = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_TopButtons.addItem(spacerItem)
        self.pushButton_Smear = QtWidgets.QPushButton(self.frame_RightPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Smear.sizePolicy().hasHeightForWidth())
        self.pushButton_Smear.setSizePolicy(sizePolicy)
        self.pushButton_Smear.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.pushButton_Smear.setFont(font)
        self.pushButton_Smear.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(16, 39, 112);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-color: rgb(102, 126, 173);\n"
"    color: rgb(172, 208, 234);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        background-color: rgb(66, 244, 223);\n"
"        color: rgb(0,0,0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: rgb(179, 241, 244);\n"
"        color: rgb(0,0,0);\n"
"}")
        self.pushButton_Smear.setObjectName("pushButton_Smear")
        self.horizontalLayout_TopButtons.addWidget(self.pushButton_Smear)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_TopButtons.addItem(spacerItem1)
        self.pushButton_Statfi = QtWidgets.QPushButton(self.frame_RightPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Statfi.sizePolicy().hasHeightForWidth())
        self.pushButton_Statfi.setSizePolicy(sizePolicy)
        self.pushButton_Statfi.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.pushButton_Statfi.setFont(font)
        self.pushButton_Statfi.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(16, 39, 112);\n"
"    border-style: outset;\n"
"    border-width: 5px;\n"
"    border-color: rgb(102, 126, 173);\n"
"    color: rgb(172, 208, 234);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        background-color: rgb(66, 244, 223);\n"
"        color: rgb(0,0,0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: rgb(179, 241, 244);\n"
"        color: rgb(0,0,0);\n"
"}")
        self.pushButton_Statfi.setObjectName("pushButton_Statfi")
        self.horizontalLayout_TopButtons.addWidget(self.pushButton_Statfi)
        spacerItem2 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_TopButtons.addItem(spacerItem2)
        self.horizontalLayout_TopButtons.setStretch(0, 19)
        self.horizontalLayout_TopButtons.setStretch(1, 12)
        self.horizontalLayout_TopButtons.setStretch(2, 1)
        self.horizontalLayout_TopButtons.setStretch(3, 12)
        self.horizontalLayout_TopButtons.setStretch(4, 19)
        self.verticalLayout_RightPanel.addLayout(self.horizontalLayout_TopButtons)
        self.frame_PlotSettings_Smear = QtWidgets.QFrame(self.frame_RightPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_PlotSettings_Smear.sizePolicy().hasHeightForWidth())
        self.frame_PlotSettings_Smear.setSizePolicy(sizePolicy)
        self.frame_PlotSettings_Smear.setMinimumSize(QtCore.QSize(0, 76))
        self.frame_PlotSettings_Smear.setStyleSheet("background-color: rgb(16, 39, 112);\n"
"border-radius: 5px;")
        self.frame_PlotSettings_Smear.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_PlotSettings_Smear.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_PlotSettings_Smear.setObjectName("frame_PlotSettings_Smear")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_PlotSettings_Smear)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_Interval = QtWidgets.QComboBox(self.frame_PlotSettings_Smear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Interval.sizePolicy().hasHeightForWidth())
        self.comboBox_Interval.setSizePolicy(sizePolicy)
        self.comboBox_Interval.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.comboBox_Interval.setFont(font)
        self.comboBox_Interval.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(89, 189, 244);")
        self.comboBox_Interval.setObjectName("comboBox_Interval")
        self.horizontalLayout.addWidget(self.comboBox_Interval)
        self.comboBox_Stations = QtWidgets.QComboBox(self.frame_PlotSettings_Smear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Stations.sizePolicy().hasHeightForWidth())
        self.comboBox_Stations.setSizePolicy(sizePolicy)
        self.comboBox_Stations.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.comboBox_Stations.setFont(font)
        self.comboBox_Stations.setAutoFillBackground(False)
        self.comboBox_Stations.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(89, 189, 244);")
        self.comboBox_Stations.setObjectName("comboBox_Stations")
        self.comboBox_Stations.addItem("")
        self.comboBox_Stations.addItem("")
        self.comboBox_Stations.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_Stations)
        self.comboBox_Variables = QtWidgets.QComboBox(self.frame_PlotSettings_Smear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Variables.sizePolicy().hasHeightForWidth())
        self.comboBox_Variables.setSizePolicy(sizePolicy)
        self.comboBox_Variables.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.comboBox_Variables.setFont(font)
        self.comboBox_Variables.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comboBox_Variables.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(89, 189, 244);")
        self.comboBox_Variables.setEditable(False)
        self.comboBox_Variables.setObjectName("comboBox_Variables")
        self.comboBox_Stations.setCurrentText("Stations")
        self.comboBox_Stations.setCurrentIndex(-1)
        self.comboBox_Interval.setCurrentIndex(-1)
        self.comboBox_Variables.setCurrentIndex(-1)
        self.horizontalLayout.addWidget(self.comboBox_Variables)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_Calendar_Smear = QtWidgets.QPushButton(self.frame_PlotSettings_Smear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Calendar_Smear.sizePolicy().hasHeightForWidth())
        self.pushButton_Calendar_Smear.setSizePolicy(sizePolicy)
        self.pushButton_Calendar_Smear.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_Calendar_Smear.setFont(font)
        self.pushButton_Calendar_Smear.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: rgb(89, 189, 244);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        background-color: rgb(66, 244, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: rgb(179, 241, 244);\n"
"}")
        self.pushButton_Calendar_Smear.setCheckable(False)
        self.pushButton_Calendar_Smear.setAutoDefault(False)
        self.pushButton_Calendar_Smear.setObjectName("pushButton_Calendar_Smear")
        self.horizontalLayout.addWidget(self.pushButton_Calendar_Smear)
        self.pushButton_Plot_Smear = QtWidgets.QPushButton(self.frame_PlotSettings_Smear)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Plot_Smear.sizePolicy().hasHeightForWidth())
        self.pushButton_Plot_Smear.setSizePolicy(sizePolicy)
        self.pushButton_Plot_Smear.setMinimumSize(QtCore.QSize(75, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_Plot_Smear.setFont(font)
        self.pushButton_Plot_Smear.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: rgb(89, 189, 244);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        background-color: rgb(66, 244, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: rgb(179, 241, 244);\n"
"}\n"
"\n"
"")
        self.pushButton_Plot_Smear.setObjectName("pushButton_Plot_Smear")
        self.horizontalLayout.addWidget(self.pushButton_Plot_Smear)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 5)
        self.horizontalLayout.setStretch(3, 32)
        self.horizontalLayout.setStretch(4, 6)
        self.horizontalLayout.setStretch(5, 4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_RightPanel.addWidget(self.frame_PlotSettings_Smear)
        self.frame_PlotSettings_Statfi = QtWidgets.QFrame(self.frame_RightPanel)
        self.frame_PlotSettings_Statfi.setMinimumSize(QtCore.QSize(0, 76))
        self.frame_PlotSettings_Statfi.setStyleSheet("background-color: rgb(16, 39, 112);\n"
"border-radius: 5px;")
        self.frame_PlotSettings_Statfi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_PlotSettings_Statfi.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_PlotSettings_Statfi.setObjectName("frame_PlotSettings_Statfi")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_PlotSettings_Statfi)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_PlotSettings_Statfi = QtWidgets.QHBoxLayout()
        self.horizontalLayout_PlotSettings_Statfi.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_PlotSettings_Statfi.setObjectName("horizontalLayout_PlotSettings_Statfi")
        self.checkBox_Volume = QtWidgets.QCheckBox(self.frame_PlotSettings_Statfi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Volume.sizePolicy().hasHeightForWidth())
        self.checkBox_Volume.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.checkBox_Volume.setFont(font)
        self.checkBox_Volume.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_Volume.setStyleSheet("QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    background-color: rgb(89, 189, 244);\n"
"}\n"
"")
        self.checkBox_Volume.setObjectName("checkBox_Volume")
        self.horizontalLayout_PlotSettings_Statfi.addWidget(self.checkBox_Volume)
        self.checkBox_Intensity = QtWidgets.QCheckBox(self.frame_PlotSettings_Statfi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Intensity.sizePolicy().hasHeightForWidth())
        self.checkBox_Intensity.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.checkBox_Intensity.setFont(font)
        self.checkBox_Intensity.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_Intensity.setStyleSheet("QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    background-color: rgb(89, 189, 244);\n"
"}")
        self.checkBox_Intensity.setObjectName("checkBox_Intensity")
        self.horizontalLayout_PlotSettings_Statfi.addWidget(self.checkBox_Intensity)
        self.checkBox_Indexed = QtWidgets.QCheckBox(self.frame_PlotSettings_Statfi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Indexed.sizePolicy().hasHeightForWidth())
        self.checkBox_Indexed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.checkBox_Indexed.setFont(font)
        self.checkBox_Indexed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_Indexed.setStyleSheet("QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    background-color: rgb(89, 189, 244);\n"
"}")
        self.checkBox_Indexed.setObjectName("checkBox_Indexed")
        self.horizontalLayout_PlotSettings_Statfi.addWidget(self.checkBox_Indexed)
        self.checkBox_IntensityIndexed = QtWidgets.QCheckBox(self.frame_PlotSettings_Statfi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_IntensityIndexed.sizePolicy().hasHeightForWidth())
        self.checkBox_IntensityIndexed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.checkBox_IntensityIndexed.setFont(font)
        self.checkBox_IntensityIndexed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_IntensityIndexed.setStyleSheet("QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    background-color: rgb(89, 189, 244);\n"
"}")
        self.checkBox_IntensityIndexed.setObjectName("checkBox_IntensityIndexed")
        self.horizontalLayout_PlotSettings_Statfi.addWidget(self.checkBox_IntensityIndexed)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_PlotSettings_Statfi.addItem(spacerItem4)
        self.pushButton_Calendar_Statfi = QtWidgets.QPushButton(self.frame_PlotSettings_Statfi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Calendar_Statfi.sizePolicy().hasHeightForWidth())
        self.pushButton_Calendar_Statfi.setSizePolicy(sizePolicy)
        self.pushButton_Calendar_Statfi.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_Calendar_Statfi.setFont(font)
        self.pushButton_Calendar_Statfi.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: rgb(89, 189, 244);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        background-color: rgb(66, 244, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: rgb(179, 241, 244);\n"
"}")
        self.pushButton_Calendar_Statfi.setCheckable(False)
        self.pushButton_Calendar_Statfi.setAutoDefault(False)
        self.pushButton_Calendar_Statfi.setObjectName("pushButton_Calendar_Statfi")
        self.horizontalLayout_PlotSettings_Statfi.addWidget(self.pushButton_Calendar_Statfi)
        self.pushButton_Plot_Statfi = QtWidgets.QPushButton(self.frame_PlotSettings_Statfi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Plot_Statfi.sizePolicy().hasHeightForWidth())
        self.pushButton_Plot_Statfi.setSizePolicy(sizePolicy)
        self.pushButton_Plot_Statfi.setMinimumSize(QtCore.QSize(75, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_Plot_Statfi.setFont(font)
        self.pushButton_Plot_Statfi.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: rgb(89, 189, 244);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        background-color: rgb(66, 244, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: rgb(179, 241, 244);\n"
"}\n"
"\n"
"")
        self.pushButton_Plot_Statfi.setObjectName("pushButton_Plot_Statfi")
        self.horizontalLayout_PlotSettings_Statfi.addWidget(self.pushButton_Plot_Statfi)
        self.horizontalLayout_PlotSettings_Statfi.setStretch(0, 27)
        self.horizontalLayout_PlotSettings_Statfi.setStretch(1, 29)
        self.horizontalLayout_PlotSettings_Statfi.setStretch(2, 27)
        self.horizontalLayout_PlotSettings_Statfi.setStretch(3, 50)
        self.horizontalLayout_PlotSettings_Statfi.setStretch(4, 160)
        self.horizontalLayout_PlotSettings_Statfi.setStretch(5, 37)
        self.horizontalLayout_PlotSettings_Statfi.setStretch(6, 25)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_PlotSettings_Statfi)
        self.verticalLayout_RightPanel.addWidget(self.frame_PlotSettings_Statfi)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_RightPanel.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_SmearPlot = QtWidgets.QWidget(self.frame_RightPanel)
        self.widget_SmearPlot.setStyleSheet("background-color: rgb(16, 39, 112);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;")
        self.widget_SmearPlot.setObjectName("widget_SmearPlot")
        self.horizontalLayout_3.addWidget(self.widget_SmearPlot)
        self.widget_StatfiPlot = QtWidgets.QWidget(self.frame_RightPanel)
        self.widget_StatfiPlot.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_StatfiPlot.setStyleSheet("background-color: rgb(16, 59, 112);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;")
        self.widget_StatfiPlot.setObjectName("widget_StatfiPlot")
        self.horizontalLayout_3.addWidget(self.widget_StatfiPlot)
        self.verticalLayout_RightPanel.addLayout(self.horizontalLayout_3)
        self.frame_PlotBottomPanel = QtWidgets.QFrame(self.frame_RightPanel)
        self.frame_PlotBottomPanel.setMinimumSize(QtCore.QSize(0, 90))
        self.frame_PlotBottomPanel.setStyleSheet("background-color: rgb(16, 39, 112);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.frame_PlotBottomPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_PlotBottomPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_PlotBottomPanel.setObjectName("frame_PlotBottomPanel")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_PlotBottomPanel)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_PlotBottomPanel = QtWidgets.QHBoxLayout()
        self.horizontalLayout_PlotBottomPanel.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_PlotBottomPanel.setObjectName("horizontalLayout_PlotBottomPanel")
        self.verticalLayout_RadioSelection = QtWidgets.QVBoxLayout()
        self.verticalLayout_RadioSelection.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_RadioSelection.setSpacing(0)
        self.verticalLayout_RadioSelection.setObjectName("verticalLayout_RadioSelection")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_RadioSelection.addItem(spacerItem6)
        self.frame_RadioSelection = QtWidgets.QFrame(self.frame_PlotBottomPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_RadioSelection.sizePolicy().hasHeightForWidth())
        self.frame_RadioSelection.setSizePolicy(sizePolicy)
        self.frame_RadioSelection.setMinimumSize(QtCore.QSize(0, 90))
        self.frame_RadioSelection.setStyleSheet("background-color: rgb(89, 189, 244);\n"
"border-radius: 5px;")
        self.frame_RadioSelection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_RadioSelection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_RadioSelection.setLineWidth(0)
        self.frame_RadioSelection.setObjectName("frame_RadioSelection")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_RadioSelection)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_RadioSelection_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_RadioSelection_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_RadioSelection_2.setSpacing(0)
        self.verticalLayout_RadioSelection_2.setObjectName("verticalLayout_RadioSelection_2")
        self.radioButton_Scatter = QtWidgets.QRadioButton(self.frame_RadioSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_Scatter.sizePolicy().hasHeightForWidth())
        self.radioButton_Scatter.setSizePolicy(sizePolicy)
        self.radioButton_Scatter.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.radioButton_Scatter.setFont(font)
        self.radioButton_Scatter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_Scatter.setStyleSheet("QRadioButton::indicator{\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}")
        self.radioButton_Scatter.setIconSize(QtCore.QSize(25, 25))
        self.radioButton_Scatter.setChecked(True)
        self.radioButton_Scatter.setObjectName("radioButton_Scatter")
        self.verticalLayout_RadioSelection_2.addWidget(self.radioButton_Scatter)
        self.radioButton_BarChart = QtWidgets.QRadioButton(self.frame_RadioSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_BarChart.sizePolicy().hasHeightForWidth())
        self.radioButton_BarChart.setSizePolicy(sizePolicy)
        self.radioButton_BarChart.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.radioButton_BarChart.setFont(font)
        self.radioButton_BarChart.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_BarChart.setStyleSheet("")
        self.radioButton_BarChart.setIconSize(QtCore.QSize(25, 25))
        self.radioButton_BarChart.setObjectName("radioButton_BarChart")
        self.verticalLayout_RadioSelection_2.addWidget(self.radioButton_BarChart)
        self.verticalLayout_3.addLayout(self.verticalLayout_RadioSelection_2)
        self.verticalLayout_RadioSelection.addWidget(self.frame_RadioSelection)
        self.verticalLayout_RadioSelection.setStretch(0, 20)
        self.horizontalLayout_PlotBottomPanel.addLayout(self.verticalLayout_RadioSelection)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_PlotBottomPanel.addItem(spacerItem7)
        self.verticalLayout_AddHistoricalData = QtWidgets.QVBoxLayout()
        self.verticalLayout_AddHistoricalData.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_AddHistoricalData.setSpacing(0)
        self.verticalLayout_AddHistoricalData.setObjectName("verticalLayout_AddHistoricalData")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_AddHistoricalData.addItem(spacerItem8)
        self.pushButton_AddHistoricalData = QtWidgets.QPushButton(self.frame_PlotBottomPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddHistoricalData.sizePolicy().hasHeightForWidth())
        self.pushButton_AddHistoricalData.setSizePolicy(sizePolicy)
        self.pushButton_AddHistoricalData.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.pushButton_AddHistoricalData.setFont(font)
        self.pushButton_AddHistoricalData.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-color: rgb(89, 189, 244);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        background-color: rgb(66, 244, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: rgb(179, 241, 244);\n"
"}")
        self.pushButton_AddHistoricalData.setObjectName("pushButton_AddHistoricalData")
        self.verticalLayout_AddHistoricalData.addWidget(self.pushButton_AddHistoricalData)
        self.verticalLayout_AddHistoricalData.setStretch(0, 20)
        self.horizontalLayout_PlotBottomPanel.addLayout(self.verticalLayout_AddHistoricalData)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_PlotBottomPanel.addItem(spacerItem9)
        self.tableView_PlotBottomTable = QtWidgets.QTableView(self.frame_PlotBottomPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_PlotBottomTable.sizePolicy().hasHeightForWidth())
        self.tableView_PlotBottomTable.setSizePolicy(sizePolicy)
        self.tableView_PlotBottomTable.setMinimumSize(QtCore.QSize(250, 100))
        self.tableView_PlotBottomTable.setStyleSheet("background-color: rgb(89, 189, 244);\n"
"border-radius: 5px;")
        self.tableView_PlotBottomTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableView_PlotBottomTable.setObjectName("tableView_PlotBottomTable")
        self.horizontalLayout_PlotBottomPanel.addWidget(self.tableView_PlotBottomTable)
        self.horizontalLayout_PlotBottomPanel.setStretch(0, 12)
        self.horizontalLayout_PlotBottomPanel.setStretch(1, 1)
        self.horizontalLayout_PlotBottomPanel.setStretch(2, 1)
        self.horizontalLayout_PlotBottomPanel.setStretch(3, 60)
        self.horizontalLayout_PlotBottomPanel.setStretch(4, 40)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_PlotBottomPanel)
        self.verticalLayout_RightPanel.addWidget(self.frame_PlotBottomPanel)
        self.horizontalLayout_BottomButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_BottomButtons.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_BottomButtons.setObjectName("horizontalLayout_BottomButtons")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_BottomButtons.addItem(spacerItem10)
        self.pushButton_SaveToFavorites = QtWidgets.QPushButton(self.frame_RightPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SaveToFavorites.sizePolicy().hasHeightForWidth())
        self.pushButton_SaveToFavorites.setSizePolicy(sizePolicy)
        self.pushButton_SaveToFavorites.setMinimumSize(QtCore.QSize(240, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_SaveToFavorites.setFont(font)
        self.pushButton_SaveToFavorites.setStyleSheet("QPushButton {\n"
"    border-radius: 2px;\n"
"    background-color: rgb(89, 189, 244);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        background-color: rgb(66, 244, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: rgb(179, 241, 244);\n"
"}")
        self.pushButton_SaveToFavorites.setObjectName("pushButton_SaveToFavorites")
        self.horizontalLayout_BottomButtons.addWidget(self.pushButton_SaveToFavorites)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_BottomButtons.addItem(spacerItem11)
        self.pushButton_ExportPlot = QtWidgets.QPushButton(self.frame_RightPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ExportPlot.sizePolicy().hasHeightForWidth())
        self.pushButton_ExportPlot.setSizePolicy(sizePolicy)
        self.pushButton_ExportPlot.setMinimumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_ExportPlot.setFont(font)
        self.pushButton_ExportPlot.setStyleSheet("QPushButton {\n"
"    border-radius: 2px;\n"
"    background-color: rgb(89, 189, 244);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        background-color: rgb(66, 244, 223);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: rgb(179, 241, 244);\n"
"}")
        self.pushButton_ExportPlot.setObjectName("pushButton_ExportPlot")
        self.horizontalLayout_BottomButtons.addWidget(self.pushButton_ExportPlot)
        self.horizontalLayout_BottomButtons.setStretch(0, 64)
        self.horizontalLayout_BottomButtons.setStretch(1, 2)
        self.horizontalLayout_BottomButtons.setStretch(2, 1)
        self.horizontalLayout_BottomButtons.setStretch(3, 2)
        self.verticalLayout_RightPanel.addLayout(self.horizontalLayout_BottomButtons)
        self.verticalLayout_RightPanel.setStretch(0, 25)
        self.verticalLayout_RightPanel.setStretch(1, 15)
        self.verticalLayout_RightPanel.setStretch(2, 15)
        self.verticalLayout_RightPanel.setStretch(3, 1)
        self.verticalLayout_RightPanel.setStretch(4, 100)
        self.verticalLayout_RightPanel.setStretch(5, 35)
        self.verticalLayout_RightPanel.setStretch(6, 15)
        self.verticalLayout_9.addLayout(self.verticalLayout_RightPanel)
        self.horizontalLayout_Main.addWidget(self.frame_RightPanel)
        self.horizontalLayout_Main.setStretch(0, 1)
        self.horizontalLayout_Main.setStretch(1, 4)
        self.gridLayout.addLayout(self.horizontalLayout_Main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_Statfi.released.connect(self.frame_PlotSettings_Smear.hide)
        self.pushButton_Smear.released.connect(self.frame_PlotSettings_Smear.show)
        self.pushButton_Statfi.released.connect(self.frame_PlotSettings_Statfi.show)
        self.pushButton_Smear.released.connect(self.frame_PlotSettings_Statfi.hide)
        self.pushButton_Smear.released.connect(self.widget_StatfiPlot.hide)
        self.pushButton_Smear.released.connect(self.widget_SmearPlot.show)
        self.pushButton_Statfi.released.connect(self.widget_SmearPlot.hide)
        self.pushButton_Statfi.released.connect(self.widget_StatfiPlot.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Favorites.setText(_translate("MainWindow", "Favorites"))
        self.label_SearchHistory.setText(_translate("MainWindow", "Search History"))
        self.pushButton_Smear.setText(_translate("MainWindow", "SMEAR"))
        self.pushButton_Statfi.setText(_translate("MainWindow", "STATFI"))
        self.comboBox_Interval.setPlaceholderText(_translate("MainWindow", " Interval"))
        self.comboBox_Stations.setPlaceholderText(_translate("MainWindow", " Stations"))
        self.comboBox_Stations.setItemText(0, _translate("MainWindow", "Test"))
        self.comboBox_Stations.setItemText(1, _translate("MainWindow", "Test1"))
        self.comboBox_Stations.setItemText(2, _translate("MainWindow", "Test2"))
        self.comboBox_Variables.setPlaceholderText(_translate("MainWindow", " Variables"))
        self.pushButton_Calendar_Smear.setText(_translate("MainWindow", "Calendar"))
        self.pushButton_Plot_Smear.setText(_translate("MainWindow", "Plot"))
        self.checkBox_Volume.setText(_translate("MainWindow", "Volume"))
        self.checkBox_Intensity.setText(_translate("MainWindow", "Intensity"))
        self.checkBox_Indexed.setText(_translate("MainWindow", "Indexed"))
        self.checkBox_IntensityIndexed.setText(_translate("MainWindow", "Intensity Indexed"))
        self.pushButton_Calendar_Statfi.setText(_translate("MainWindow", "Calendar"))
        self.pushButton_Plot_Statfi.setText(_translate("MainWindow", "Plot"))
        self.radioButton_Scatter.setText(_translate("MainWindow", "Scatter"))
        self.radioButton_BarChart.setText(_translate("MainWindow", "BarChart"))
        self.pushButton_AddHistoricalData.setText(_translate("MainWindow", "Add \n"
"Historical\n"
" Data"))
        self.pushButton_SaveToFavorites.setText(_translate("MainWindow", "Save to Favorites"))
        self.pushButton_ExportPlot.setText(_translate("MainWindow", "Export plot"))
        self.widget_StatfiPlot.hide()
        self.frame_PlotSettings_Statfi.hide()
